System notification
Tributerre/LivrETS-Web pull request #60
Opened 2016-10-15 03:55 UTC by willkoua

pour faire marcher ce systeme, il faudrait créer certaines propriétés
SMTP_CLIENT = pour le serveur SMTP
EMAIL_PWD = pour le mot de passe de votre compte mail par lequelle vous passez pour envoyer des mails 
EMAIL_USERNAME = pour le username du compte d'envoie
EMIAL_PROVIDER = pour l'email d'envoie.

J'ai aussi modifié légèrement le model en ajoutant un champs `listUser` (liste des mails à qui ont doit envoyer la notification) dans le `NotificationManager` pour récupérer la liste des mails (Je la modifierais dans le diagramme lorsque tu auras validé la PR) 

Les mails sont écrit directement dans des fichiers texte.

2016-10-22 00:28 UTC, krazdax5 commented
ces infos devraient être dans web.sample.config et être référencer depuis là où tu l'utilises. À faire avant merge stp :)

2016-10-22 00:30 UTC, krazdax5 requested changes
Mettre les infos d'exemple de config smtp dans web.sample.config (là où sont les infos pour le compte google) + aller chercher cette config pour envoyer des courriels

2016-10-25 03:40 UTC, willkoua commented
Ajout d'un nouveau paramètres au fichier de web.config 
`<add key="EMAIL_PORT" value="587" />`

2016-10-26 23:02 UTC, krazdax5 approved these changes

2016-10-26 23:02 UTC, merged